Update workflow

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -14,30 +14,28 @@ jobs:
 
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
       - name: Install Docker Compose
-        if: always()
         run: |
-          # Install docker-compose
-          sudo curl -L "https://github.com/docker/compose/releases/download/v2.29.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose          
-          echo "Docker installed"
-          sudo chmod +x /usr/local/bin/docker-compose
-          echo "runnable"
+          sudo apt-get update
+          sudo apt-get install -y docker-compose
           docker-compose version
 
       - name: Start Odoo
         run: |
           docker-compose up -d
           echo "Waiting for Odoo to start..."
-          for i in {1..10}; do
-            if curl -s http://localhost:8069 | grep -q "<title>Odoo</title>"; then
-              echo "Odoo is up!"
-              break
+          for i in {1..30}; do
+            if docker-compose logs odoo | grep -q "HTTP service (werkzeug) running"; then
+              echo "Odoo is ready!"
+              exit 0
             fi
-            echo "Waiting for Odoo..."
+            echo "Still waiting..."
             sleep 10
           done
+          echo "Odoo failed to start in time."
+          exit 1
 
       - name: Verify Odoo is Running
         run: curl -I http://localhost:8069
@@ -53,17 +51,13 @@ jobs:
           pip install -r requirements.txt
 
       - name: Install Chrome and ChromeDriver
+        uses: browser-actions/setup-chrome@v1
+        with:
+          chrome-version: stable
+          chromedriver-version: matching
+
+      - name: Verify Chrome & ChromeDriver
         run: |
-          sudo apt-get update
-          sudo apt-get install -y wget unzip
-          wget -q -O google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
-          sudo dpkg -i google-chrome.deb || sudo apt-get -f install -y
-          CHROME_VERSION=$(google-chrome --version | grep -oP '[0-9]+\.[0-9]+\.[0-9]+')
-          DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
-          wget -q "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip"
-          unzip chromedriver_linux64.zip
-          sudo mv chromedriver /usr/local/bin/
-          sudo chmod +x /usr/local/bin/chromedriver
           google-chrome --version
           chromedriver --version
 
